-- Paso 1: datos comerciales y RBAC. No elimina las columnas legacy de tenants/users.
BEGIN;
CREATE TABLE IF NOT EXISTS plans (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, currency CHAR(3) NOT NULL, unit_amount NUMERIC(12,2) NOT NULL CHECK(unit_amount >= 0), billing_interval TEXT NOT NULL CHECK(billing_interval IN ('monthly','yearly')), tax_included BOOLEAN NOT NULL DEFAULT FALSE, max_seats INT, max_active_publications INT, max_storage_bytes BIGINT, max_import_jobs_period INT, max_import_pages_period INT, is_sellable BOOLEAN NOT NULL DEFAULT TRUE, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), scope TEXT NOT NULL CHECK(scope IN ('platform','tenant')), code TEXT NOT NULL, name TEXT NOT NULL, rank INT NOT NULL DEFAULT 0, is_system BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE(scope, code));
CREATE TABLE IF NOT EXISTS tenant_subscriptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, plan_id UUID NOT NULL REFERENCES plans(id), status TEXT NOT NULL CHECK(status IN ('trial','active','grace','past_due','suspended','cancelled','expired')), currency CHAR(3) NOT NULL, unit_amount NUMERIC(12,2) NOT NULL, billing_interval TEXT NOT NULL CHECK(billing_interval IN ('monthly','yearly')), tax_included BOOLEAN NOT NULL DEFAULT FALSE, limits_snapshot JSONB NOT NULL DEFAULT '{}', source TEXT NOT NULL DEFAULT 'superadmin', starts_at TIMESTAMPTZ NOT NULL DEFAULT now(), ends_at TIMESTAMPTZ, grace_ends_at TIMESTAMPTZ, cancelled_at TIMESTAMPTZ, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS uq_tenant_current_subscription ON tenant_subscriptions(tenant_id) WHERE status IN ('trial','active','grace','past_due','suspended');
CREATE TABLE IF NOT EXISTS tenant_usage (tenant_id UUID PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE, storage_bytes BIGINT NOT NULL DEFAULT 0 CHECK(storage_bytes >= 0), active_publications INT NOT NULL DEFAULT 0 CHECK(active_publications >= 0), seats INT NOT NULL DEFAULT 0 CHECK(seats >= 0), import_jobs_period INT NOT NULL DEFAULT 0, import_pages_period INT NOT NULL DEFAULT 0, reader_views_period BIGINT NOT NULL DEFAULT 0, egress_bytes_period BIGINT NOT NULL DEFAULT 0, period_started_at TIMESTAMPTZ NOT NULL DEFAULT now(), measured_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tenant_domains (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, hostname TEXT NOT NULL UNIQUE, kind TEXT NOT NULL CHECK(kind IN ('platform_subdomain','custom')), is_primary BOOLEAN NOT NULL DEFAULT TRUE, status TEXT NOT NULL CHECK(status IN ('pending','verifying','verified','failed','disabled')), verification_token_hash TEXT, verified_at TIMESTAMPTZ, tls_status TEXT NOT NULL DEFAULT 'not_requested', last_checked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS uq_tenant_primary_domain ON tenant_domains(tenant_id) WHERE is_primary;
CREATE TABLE IF NOT EXISTS user_platform_roles (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, role_id UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE, assigned_by UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(user_id, role_id));
CREATE TABLE IF NOT EXISTS tenant_memberships (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, role_id UUID NOT NULL REFERENCES roles(id), status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('invited','active','revoked')), invited_by UUID REFERENCES users(id), invite_token_hash TEXT, invite_expires_at TIMESTAMPTZ, accepted_at TIMESTAMPTZ, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(tenant_id,user_id));
INSERT INTO roles(scope,code,name,rank) VALUES ('platform','superadmin','Super Admin CETRIX',100),('tenant','owner','Propietario',90),('tenant','admin','Administrador',70),('tenant','editor','Editor',50),('tenant','reviewer','Revisor',30),('tenant','reader','Lector',10) ON CONFLICT(scope,code) DO NOTHING;
INSERT INTO plans(code,name,currency,unit_amount,billing_interval,max_seats,max_active_publications,max_storage_bytes) VALUES ('inicio','Inicio','MXN',1490,'monthly',2,10,2147483648),('professional','Profesional','MXN',3490,'monthly',5,40,10737418240),('business','Business','MXN',7990,'monthly',15,150,53687091200),('enterprise','Enterprise','MXN',15000,'monthly',NULL,NULL,214748364800) ON CONFLICT(code) DO NOTHING;
INSERT INTO tenant_memberships(tenant_id,user_id,role_id,status,accepted_at) SELECT u.tenant_id,u.id,r.id,'active',now() FROM users u JOIN roles r ON r.scope='tenant' AND r.code=CASE WHEN u.role='admin' THEN 'admin' WHEN u.role='viewer' THEN 'reader' ELSE 'editor' END ON CONFLICT(tenant_id,user_id) DO NOTHING;
INSERT INTO tenant_usage(tenant_id,storage_bytes,active_publications,seats) SELECT t.id,COALESCE((SELECT SUM(a.size_bytes) FROM assets a WHERE a.tenant_id=t.id),0),COALESCE((SELECT COUNT(*) FROM publications p WHERE p.tenant_id=t.id AND p.status <> 'archived'),0),COALESCE((SELECT COUNT(*) FROM users u WHERE u.tenant_id=t.id AND u.is_active),0) FROM tenants t ON CONFLICT(tenant_id) DO NOTHING;
INSERT INTO tenant_domains(tenant_id,hostname,kind,status,verified_at) SELECT id,subdomain,'platform_subdomain','verified',now() FROM tenants ON CONFLICT(hostname) DO NOTHING;
COMMIT;
