import React, { useEffect, useState } from 'react';
import api from '../services/api';
import { useAuth } from '../services/AuthContext';

export default function SuperAdmin() {
  const { user } = useAuth(); const [data, setData] = useState(null); const [plans, setPlans] = useState([]); const [error, setError] = useState(''); const [form, setForm] = useState({name:'', subdomain:'', plan_code:'professional'});
  const load = () => api.get('/api/superadmin/overview').then(r => setData(r.data)).catch(e => setError(e.response?.data?.detail || 'No autorizado'));
  useEffect(() => { load(); api.get('/api/superadmin/plans').then(r => setPlans(r.data)); }, []);
  const createTenant = async (e) => { e.preventDefault(); try { await api.post('/api/superadmin/tenants', form); setForm({name:'',subdomain:'',plan_code:'professional'}); load(); } catch(e) { setError(e.response?.data?.detail || 'No se pudo crear el tenant'); } };
  const toggle = async (tenant) => { await api.patch(`/api/superadmin/tenants/${tenant.id}/status`, {status: tenant.status === 'active' ? 'suspended' : 'active'}); load(); };
  if (error) return <main className="page-container"><h2>Panel Super Admin CETRIX</h2><p>{error}</p><p>Tu cuenta aún debe recibir el rol global <code>superadmin</code>; no se asigna automáticamente por seguridad.</p></main>;
  return <main className="page-container"><h2>Panel Super Admin CETRIX</h2><p>Tenants, consumo y contratos. Sesión: {user?.email}</p><form onSubmit={createTenant} style={{display:'flex',gap:8,flexWrap:'wrap',margin:'1rem 0'}}><input required placeholder="Empresa" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="subdominio" value={form.subdomain} onChange={e=>setForm({...form,subdomain:e.target.value.toLowerCase()})}/><select value={form.plan_code} onChange={e=>setForm({...form,plan_code:e.target.value})}>{plans.filter(p=>p.is_sellable&&p.is_active).map(p=><option key={p.code} value={p.code}>{p.name} · {p.currency} {p.unit_amount}</option>)}</select><button type="submit">Crear tenant</button></form>{!data ? <p>Cargando…</p> : <table><thead><tr><th>Empresa</th><th>Estado</th><th>Plan</th><th>Consumo</th><th>Acción</th></tr></thead><tbody>{data.tenants.map(t => <tr key={t.id}><td>{t.name}<br/><small>{t.subdomain}</small></td><td>{t.status}</td><td>{t.subscription ? `${t.subscription.plan} · ${t.subscription.currency} ${t.subscription.unit_amount}` : 'Sin suscripción'}</td><td>{t.usage.seats} seats · {t.usage.active_publications} publicaciones · {t.usage.storage_bytes} bytes</td><td><button onClick={()=>toggle(t)}>{t.status === 'active' ? 'Suspender' : 'Reactivar'}</button></td></tr>)}</tbody></table>}</main>;
}
