import React, { useEffect, useState } from 'react';
import api from '../services/api';
import { useAuth } from '../services/AuthContext';
import '../styles/SuperAdmin.css';

const formatBytes = (bytes = 0) => {
  if (!bytes) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB', 'TB']; let index = 0; let value = bytes;
  while (value >= 1024 && index < units.length - 1) { value /= 1024; index += 1; }
  return `${value.toFixed(index ? 1 : 0)} ${units[index]}`;
};

export default function SuperAdmin() {
  const { user } = useAuth(); const [data, setData] = useState(null); const [plans, setPlans] = useState([]); const [error, setError] = useState(''); const [form, setForm] = useState({name:'', subdomain:'', plan_code:'professional'}); const [ownerEmail, setOwnerEmail] = useState(''); const [invite, setInvite] = useState('');
  const load = () => api.get('/api/superadmin/overview').then(r => setData(r.data)).catch(e => setError(e.response?.data?.detail || 'No autorizado'));
  useEffect(() => { load(); api.get('/api/superadmin/plans').then(r => setPlans(r.data)); }, []);
  const createTenant = async (e) => { e.preventDefault(); try { await api.post('/api/superadmin/tenants', form); setForm({name:'',subdomain:'',plan_code:'professional'}); load(); } catch(e) { setError(e.response?.data?.detail || 'No se pudo crear el tenant'); } };
  const toggle = async (tenant) => { await api.patch(`/api/superadmin/tenants/${tenant.id}/status`, {status: tenant.status === 'active' ? 'suspended' : 'active'}); load(); };
  const inviteOwner = async (tenant) => { if (!ownerEmail) return setError('Introduce el correo del propietario'); try { const r=await api.post(`/api/superadmin/tenants/${tenant.id}/owner-invitations`, {email:ownerEmail}); setInvite(`${window.location.origin}/aceptar-invitacion?token=${r.data.invite_token}`); setOwnerEmail(''); } catch(e) { setError(e.response?.data?.detail || 'No se pudo crear la invitación'); } };
  if (error) return <main className="superadmin-page"><div className="superadmin-error"><h2>Acceso Super Admin</h2><p>{error}</p></div></main>;
  const totals = (data?.tenants || []).reduce((sum, tenant) => ({ tenants: sum.tenants + 1, seats: sum.seats + tenant.usage.seats, storage: sum.storage + tenant.usage.storage_bytes }), { tenants: 0, seats: 0, storage: 0 });
  return <main className="superadmin-page"><header className="superadmin-hero"><div><span className="superadmin-eyebrow">CETRIX SOFTWARE · OPERACIÓN</span><h2>Administración de plataforma</h2><p>Gestiona empresas, contratos, consumo y accesos de forma centralizada.</p></div><div className="superadmin-session">Sesión Super Admin<br/><strong>{user?.email}</strong></div></header>
    <section className="superadmin-stats"><article><span>Empresas</span><strong>{totals.tenants}</strong></article><article><span>Usuarios asignados</span><strong>{totals.seats}</strong></article><article><span>Almacenamiento usado</span><strong>{formatBytes(totals.storage)}</strong></article></section>
    <section className="superadmin-card"><div className="section-heading"><div><span className="section-kicker">ALTA CONTROLADA</span><h3>Nueva empresa</h3></div><p>El propietario se invita después; nunca se asignan contraseñas.</p></div><form className="tenant-form" onSubmit={createTenant}><label>Empresa<input required placeholder="Ej. Editorial Horizonte" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Subdominio<input required placeholder="editorial-horizonte" value={form.subdomain} onChange={e=>setForm({...form,subdomain:e.target.value.toLowerCase()})}/></label><label>Plan<select value={form.plan_code} onChange={e=>setForm({...form,plan_code:e.target.value})}>{plans.filter(p=>p.is_sellable&&p.is_active).map(p=><option key={p.code} value={p.code}>{p.name} · {p.currency} {p.unit_amount}</option>)}</select></label><button className="primary-action" type="submit">Crear empresa</button></form></section>
    {invite && <section className="superadmin-invite"><strong>Invitación creada</strong><p>Comparte este enlace solo con el propietario, antes de que caduque.</p><code>{invite}</code></section>}
    <section className="superadmin-card"><div className="section-heading"><div><span className="section-kicker">CARTERA ACTIVA</span><h3>Empresas registradas</h3></div><p>{data ? `${data.tenants.length} empresa(s) gestionada(s)` : 'Cargando información…'}</p></div>{!data ? <div className="superadmin-loading">Cargando panel…</div> : <div className="tenant-table-wrap"><table className="tenant-table"><thead><tr><th>Empresa</th><th>Estado</th><th>Contrato</th><th>Consumo</th><th>Gestión</th></tr></thead><tbody>{data.tenants.map(t => <tr key={t.id}><td><strong>{t.name}</strong><small>{t.subdomain}</small></td><td><span className={`status-pill ${t.status}`}>{t.status === 'active' ? 'Activa' : 'Suspendida'}</span></td><td>{t.subscription ? <><strong>{t.subscription.plan}</strong><small>{t.subscription.currency} {t.subscription.unit_amount} / mes</small></> : <span className="muted">Sin suscripción</span>}</td><td><strong>{formatBytes(t.usage.storage_bytes)}</strong><small>{t.usage.seats} seats · {t.usage.active_publications} publicaciones</small></td><td><div className="tenant-actions"><button className="secondary-action" onClick={()=>toggle(t)}>{t.status === 'active' ? 'Suspender' : 'Reactivar'}</button><div className="invite-inline"><input type="email" placeholder="owner@empresa.com" value={ownerEmail} onChange={e=>setOwnerEmail(e.target.value)}/><button className="link-action" onClick={()=>inviteOwner(t)}>Invitar owner</button></div></div></td></tr>)}</tbody></table></div>}</section></main>;
}
